services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3Monitor\T3monitoring\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  T3Monitor\T3monitoring\Domain\Model\Dto\EmMonitoringConfiguration:
    public: true

  T3Monitor\T3monitoring\Service\Import\:
    resource: '../Classes/Service/Import/*'
    public: true

  T3Monitor\T3monitoring\Service\DataIntegrity:
    public: true

  T3Monitor\T3monitoring\Notification\EmailNotification:
    public: true

  T3Monitor\T3monitoring\Domain\TypeConverter\ClientFilterDemandConverter:
    tags:
      - name: extbase.type_converter
        priority: 10
        target: T3Monitor\T3monitoring\Domain\Model\Dto\ClientFilterDemand
        sources: array,string
